### ISSUE TITLE
Add 2015 areal images

### ISSUE THREAD

**Issue by tordans** [codeforberlin/fis-broker#1]
See https://github.com/osmlab/editor-layer-index/pull/525 for details.

**Comment by jochenklar** [comment]
Hi, the 2015 images are not listed on the fis broker anymore, but a direct link works: https://fbinter.stadt-berlin.de/fb/berlin/service.jsp?id=a_luftbild2015_rgb@senstadt&type=FEED. Also 2018 images are available now. I will try to work on it over the weekend.

**Comment by tordans** [comment]
Yeah, 2018 images, awesome!

Link: http://fbinter.stadt-berlin.de/fb/index.jsp?loginkey=zoomStart&mapId=k_luftbild2018_rgb@senstadt

Wenn die Daten da sind, mache ich gerne den PR für den OSM Editor Layer Index.

Noch eine Frage: Für den [OSM Editor Layer Index](https://github.com/osmlab/editor-layer-index) braucht man ein GeoJSON das die Grenzen der Bilder beschreibt. Kannst Du das beim Auslesen direkt mit generieren? Ich würde sonst einfach das nehmen was auch für die letzten Jahre verwendet wurde; keine Ahnung wie gut das die Bilder-Grenzen abbildet.

<img width="209" alt="bildschirmfoto 2018-08-16 um 21 33 42" src="https://user-images.githubusercontent.com/111561/44230694-286cf700-a19c-11e8-8c5c-dd9326087b0a.png">

**Comment by grischard** [comment]
Die Polygone kann man auch [automatisch generieren](https://github.com/osmlab/editor-layer-index/commit/487c94bb46ca6e4fedd944d5b483ca7f83aedc3c#commitcomment-29473438), besonders wenn man schon mit einem geotiff zu tun hat.

**Comment by jochenklar** [comment]
Ok, sollte jetzt gehen:

https://tiles.codefor.de/berlin-2015/{z}/{x}/{y}.png
https://tiles.codefor.de/berlin-2018/{z}/{x}/{y}.png

**Comment by jochenklar** [comment]
das mit dem polygon ist schwieriger. `gdal_polygonize.py` will alle tiffs in den speicher laden und swappt dann wie blöde. Die Bilder haben ja informationen über ihre Ecken, zur Not könnte mal was schreiben was das ausliesst. Ihr brauch sowas wie hier: http://fbarc.stadt-berlin.de/FIS_Broker_Atom/DOP/Blattschnitt2x2km.gif, nur als json oder?

**Comment by tordans** [comment]
@jochenklar vielen Dank!

> Ihr brauch sowas wie hier: http://fbarc.stadt-berlin.de/FIS_Broker_Atom/DOP/Blattschnitt2x2km.gif, nur als json oder?

Richtig. Manuell habe ich es nicht geschafft das nachzuzeichnen.
Es soll dann so aussehen:
- https://github.com/osmlab/editor-layer-index/blob/300329f75f6f098f97b5df83bede54fa1e277cd8/sources/europe/de/Berlinaerialphotograph2018.geojson
- Zeichnen kann man es scheinbar mit http://geojson.io/#map=10/52.5083/13.4184
